version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=
      - DEBUG=
      - ENVIRONMENT=
      - POSTGRES_NAME=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_PASSWORD=
    volumes:
      - postgres_celery_redis:/var/lib/postgresql/data/
  celery:
    build: .
    command: celery -A core worker -l INFO
    environment:
      - SECRET_KEY=
      - DEBUG=
      - ENVIRONMENT=
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/code
    depends_on:
      - web
      - db
      - redis

  redis:
    image: redis:alpine

volumes:
  postgres_celery_redis: